/* This file is automatically generated by OpenApp. */

var abp = abp || {};
abp.schemas = abp.schemas || {};

// module 'app'
(function () {

    abp.schemas.app = abp.schemas.app || {};

    // controller 'tokenAuth'
    abp.schemas.app.tokenAuth = abp.schemas.app.tokenAuth || {};
    // action 'authenticate'
    abp.schemas.app.tokenAuth.authenticate = abp.schemas.app.tokenAuth.authenticate || {};
    abp.schemas.app.tokenAuth.authenticate.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "AuthenticateResultModel",
        "type": "object",
        "properties": {
            "accessToken": {
                "type": "string"
            },
            "encryptedAccessToken": {
                "type": "string"
            },
            "expireInSeconds": {
                "type": "integer",
                "format": "int32"
            },
            "userId": {
                "type": "integer",
                "format": "int64"
            }
        }
    }
    abp.schemas.app.tokenAuth.authenticate.parameters = {
        model: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "AuthenticateModel",
            "type": "object",
            "required": [
                "userNameOrEmailAddress",
                "password"
            ],
            "properties": {
                "userNameOrEmailAddress": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0
                },
                "rememberClient": {
                    "type": "boolean"
                }
            }
        },
    };
    // action 'getExternalAuthenticationProviders'
    abp.schemas.app.tokenAuth.getExternalAuthenticationProviders = abp.schemas.app.tokenAuth.getExternalAuthenticationProviders || {};
    abp.schemas.app.tokenAuth.getExternalAuthenticationProviders.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ListOfExternalLoginProviderInfoModel",
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                }
            }
        }
    }
    // action 'externalAuthenticate'
    abp.schemas.app.tokenAuth.externalAuthenticate = abp.schemas.app.tokenAuth.externalAuthenticate || {};
    abp.schemas.app.tokenAuth.externalAuthenticate.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ExternalAuthenticateResultModel",
        "type": "object",
        "properties": {
            "accessToken": {
                "type": "string"
            },
            "encryptedAccessToken": {
                "type": "string"
            },
            "expireInSeconds": {
                "type": "integer",
                "format": "int32"
            },
            "waitingForActivation": {
                "type": "boolean"
            }
        }
    }
    abp.schemas.app.tokenAuth.externalAuthenticate.parameters = {
        model: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "ExternalAuthenticateModel",
            "type": "object",
            "required": [
                "authProvider",
                "providerKey",
                "providerAccessCode"
            ],
            "properties": {
                "authProvider": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0
                },
                "providerKey": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0
                },
                "providerAccessCode": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
    };

    // controller 'impersonate'
    abp.schemas.app.impersonate = abp.schemas.app.impersonate || {};
    // action 'impersonate'
    abp.schemas.app.impersonate.impersonate = abp.schemas.app.impersonate.impersonate || {};
    abp.schemas.app.impersonate.impersonate.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "String",
        "type": "string"
    }
    abp.schemas.app.impersonate.impersonate.parameters = {
        model: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "ImpersonateModel",
            "type": "object",
            "properties": {
                "tenantId": {
                    "type": "integer",
                    "format": "int32"
                },
                "userId": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
    };
    // action 'impersonateTenant'
    abp.schemas.app.impersonate.impersonateTenant = abp.schemas.app.impersonate.impersonateTenant || {};
    abp.schemas.app.impersonate.impersonateTenant.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "String",
        "type": "string"
    }
    abp.schemas.app.impersonate.impersonateTenant.parameters = {
        tenantId: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "Int32",
            "type": "integer",
            "format": "int32"
        },
    };
    // action 'backToImpersonator'
    abp.schemas.app.impersonate.backToImpersonator = abp.schemas.app.impersonate.backToImpersonator || {};
    abp.schemas.app.impersonate.backToImpersonator.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "String",
        "type": "string"
    }

    // controller 'demo1Service'
    abp.schemas.app.demo1Service = abp.schemas.app.demo1Service || {};
    // action 'getMyGreeting'
    abp.schemas.app.demo1Service.getMyGreeting = abp.schemas.app.demo1Service.getMyGreeting || {};
    abp.schemas.app.demo1Service.getMyGreeting.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "String",
        "type": "string"
    }
    // action 'sendNotification'
    abp.schemas.app.demo1Service.sendNotification = abp.schemas.app.demo1Service.sendNotification || {};
    abp.schemas.app.demo1Service.sendNotification.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "Void",
        "type": "object"
    }
    abp.schemas.app.demo1Service.sendNotification.parameters = {
        message: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "String",
            "type": "string"
        },
    };

    // controller 'user'
    abp.schemas.app.user = abp.schemas.app.user || {};
    // action 'create'
    abp.schemas.app.user.create = abp.schemas.app.user.create || {};
    abp.schemas.app.user.create.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "UserDto",
        "type": "object",
        "required": [
            "userName",
            "name",
            "surname",
            "emailAddress"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int64"
            },
            "userName": {
                "type": "string",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "title": {
                "type": "string",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid": false
            },
            "name": {
                "title": "Firstname",
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": false
            },
            "surname": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": false
            },
            "emailAddress": {
                "type": "string",
                "format": "email",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "phoneNumber": {
                "type": "string",
                "maxLength": 32,
                "minLength": 0,
                "x-ui-grid": false
            },
            "isActive": {
                "type": "boolean",
                "x-ui-grid-sortable": true
            },
            "fullName": {
                "type": "string",
                "readonly": true,
                "x-ui-grid-sortable": true
            },
            "lastLoginTime": {
                "type": "string",
                "readonly": true,
                "format": "date-time",
                "x-ui-grid": false
            },
            "creationTime": {
                "type": "string",
                "readonly": true,
                "format": "date-time",
                "x-ui-grid": false
            },
            "roleNames": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            },
            "tenantId": {
                "type": "integer",
                "readonly": true,
                "format": "int32",
                "x-ui-grid": false
            },
            "canDelete": {
                "type": "boolean",
                "x-ui-grid": false
            },
            "customActions": {
                "type": "array",
                "readonly": true,
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.user.create.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "CreateUserDto",
            "type": "object",
            "required": [
                "userName",
                "name",
                "surname",
                "emailAddress",
                "password"
            ],
            "properties": {
                "userName": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0
                },
                "title": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0,
                    "x-ui-grid": false
                },
                "name": {
                    "title": "Firstname",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "surname": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "emailAddress": {
                    "type": "string",
                    "format": "email",
                    "maxLength": 256,
                    "minLength": 0
                },
                "phoneNumber": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0,
                    "x-ui-grid": false
                },
                "isActive": {
                    "type": "boolean"
                },
                "roleNames": {
                    "title": "Roles",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-enum-action": "getRoles",
                    "x-enum-valuefield": "normalizedName",
                    "x-enum-textfield": "displayName"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0
                }
            }
        },
    };
    // action 'update'
    abp.schemas.app.user.update = abp.schemas.app.user.update || {};
    abp.schemas.app.user.update.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "UserDto",
        "type": "object",
        "required": [
            "userName",
            "name",
            "surname",
            "emailAddress"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int64"
            },
            "userName": {
                "type": "string",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "title": {
                "type": "string",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid": false
            },
            "name": {
                "title": "Firstname",
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": false
            },
            "surname": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": false
            },
            "emailAddress": {
                "type": "string",
                "format": "email",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "phoneNumber": {
                "type": "string",
                "maxLength": 32,
                "minLength": 0,
                "x-ui-grid": false
            },
            "isActive": {
                "type": "boolean",
                "x-ui-grid-sortable": true
            },
            "fullName": {
                "type": "string",
                "readonly": true,
                "x-ui-grid-sortable": true
            },
            "lastLoginTime": {
                "type": "string",
                "readonly": true,
                "format": "date-time",
                "x-ui-grid": false
            },
            "creationTime": {
                "type": "string",
                "readonly": true,
                "format": "date-time",
                "x-ui-grid": false
            },
            "roleNames": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            },
            "tenantId": {
                "type": "integer",
                "readonly": true,
                "format": "int32",
                "x-ui-grid": false
            },
            "canDelete": {
                "type": "boolean",
                "x-ui-grid": false
            },
            "customActions": {
                "type": "array",
                "readonly": true,
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.user.update.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "UpdateUserDto",
            "type": "object",
            "required": [
                "userName",
                "name",
                "surname",
                "emailAddress"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "userName": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0
                },
                "title": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0,
                    "x-ui-grid": false
                },
                "name": {
                    "title": "Firstname",
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "surname": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "emailAddress": {
                    "type": "string",
                    "format": "email",
                    "maxLength": 256,
                    "minLength": 0
                },
                "phoneNumber": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0,
                    "x-ui-grid": false
                },
                "isActive": {
                    "type": "boolean"
                },
                "roleNames": {
                    "title": "Roles",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-enum-action": "getRoles",
                    "x-enum-valuefield": "normalizedName",
                    "x-enum-textfield": "displayName"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0
                }
            }
        },
    };
    // action 'delete'
    abp.schemas.app.user.delete = abp.schemas.app.user.delete || {};
    abp.schemas.app.user.delete.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt64",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
    };
    // action 'getRoles'
    abp.schemas.app.user.getRoles = abp.schemas.app.user.getRoles || {};
    abp.schemas.app.user.getRoles.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ListResultDtoOfRoleDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "name",
                        "displayName"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "name": {
                            "title": "RoleName",
                            "type": "string",
                            "maxLength": 32,
                            "minLength": 0,
                            "x-ui-grid": true
                        },
                        "displayName": {
                            "title": "DisplayName",
                            "type": "string",
                            "maxLength": 64,
                            "minLength": 0,
                            "x-ui-grid": true
                        },
                        "normalizedName": {
                            "type": "string",
                            "x-ui-grid": false
                        },
                        "description": {
                            "type": "string",
                            "maxLength": 5000,
                            "minLength": 0,
                            "x-ui-grid": false
                        },
                        "isStatic": {
                            "type": "boolean",
                            "x-ui-grid": false
                        },
                        "permissions": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "x-ui-grid": false
                        }
                    }
                }
            }
        }
    }
    // action 'changeLanguage'
    abp.schemas.app.user.changeLanguage = abp.schemas.app.user.changeLanguage || {};
    abp.schemas.app.user.changeLanguage.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "ChangeUserLanguageDto",
            "type": "object",
            "required": [
                "languageName"
            ],
            "properties": {
                "languageName": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
    };
    // action 'get'
    abp.schemas.app.user.get = abp.schemas.app.user.get || {};
    abp.schemas.app.user.get.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "UserDto",
        "type": "object",
        "required": [
            "userName",
            "name",
            "surname",
            "emailAddress"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int64"
            },
            "userName": {
                "type": "string",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "title": {
                "type": "string",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid": false
            },
            "name": {
                "title": "Firstname",
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": false
            },
            "surname": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": false
            },
            "emailAddress": {
                "type": "string",
                "format": "email",
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "phoneNumber": {
                "type": "string",
                "maxLength": 32,
                "minLength": 0,
                "x-ui-grid": false
            },
            "isActive": {
                "type": "boolean",
                "x-ui-grid-sortable": true
            },
            "fullName": {
                "type": "string",
                "readonly": true,
                "x-ui-grid-sortable": true
            },
            "lastLoginTime": {
                "type": "string",
                "readonly": true,
                "format": "date-time",
                "x-ui-grid": false
            },
            "creationTime": {
                "type": "string",
                "readonly": true,
                "format": "date-time",
                "x-ui-grid": false
            },
            "roleNames": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            },
            "tenantId": {
                "type": "integer",
                "readonly": true,
                "format": "int32",
                "x-ui-grid": false
            },
            "canDelete": {
                "type": "boolean",
                "x-ui-grid": false
            },
            "customActions": {
                "type": "array",
                "readonly": true,
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.user.get.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt64",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
    };
    // action 'getAll'
    abp.schemas.app.user.getAll = abp.schemas.app.user.getAll || {};
    abp.schemas.app.user.getAll.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "PagedResultDtoOfUserDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "userName",
                        "name",
                        "surname",
                        "emailAddress"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "userName": {
                            "type": "string",
                            "maxLength": 256,
                            "minLength": 0,
                            "x-ui-grid-sortable": true
                        },
                        "title": {
                            "type": "string",
                            "maxLength": 256,
                            "minLength": 0,
                            "x-ui-grid": false
                        },
                        "name": {
                            "title": "Firstname",
                            "type": "string",
                            "maxLength": 64,
                            "minLength": 0,
                            "x-ui-grid": false
                        },
                        "surname": {
                            "type": "string",
                            "maxLength": 64,
                            "minLength": 0,
                            "x-ui-grid": false
                        },
                        "emailAddress": {
                            "type": "string",
                            "format": "email",
                            "maxLength": 256,
                            "minLength": 0,
                            "x-ui-grid-sortable": true
                        },
                        "phoneNumber": {
                            "type": "string",
                            "maxLength": 32,
                            "minLength": 0,
                            "x-ui-grid": false
                        },
                        "isActive": {
                            "type": "boolean",
                            "x-ui-grid-sortable": true
                        },
                        "fullName": {
                            "type": "string",
                            "readonly": true,
                            "x-ui-grid-sortable": true
                        },
                        "lastLoginTime": {
                            "type": "string",
                            "readonly": true,
                            "format": "date-time",
                            "x-ui-grid": false
                        },
                        "creationTime": {
                            "type": "string",
                            "readonly": true,
                            "format": "date-time",
                            "x-ui-grid": false
                        },
                        "roleNames": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "x-ui-grid": false
                        },
                        "tenantId": {
                            "type": "integer",
                            "readonly": true,
                            "format": "int32",
                            "x-ui-grid": false
                        },
                        "canDelete": {
                            "type": "boolean",
                            "x-ui-grid": false
                        },
                        "customActions": {
                            "type": "array",
                            "readonly": true,
                            "items": {
                                "type": "string"
                            },
                            "x-ui-grid": false
                        }
                    }
                }
            },
            "totalCount": {
                "type": "integer",
                "format": "int32"
            }
        }
    }
    abp.schemas.app.user.getAll.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "UsersResultRequestDto",
            "type": "object",
            "properties": {
                "sorting": {
                    "type": "string"
                },
                "skipCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 0.0
                },
                "maxResultCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 1.0
                },
                "userName": {
                    "type": "string",
                    "x-ui-filter-eager": true
                },
                "email": {
                    "type": "string",
                    "x-ui-filter-eager": true
                }
            }
        },
    };

    // controller 'session'
    abp.schemas.app.session = abp.schemas.app.session || {};
    // action 'getCurrentLoginInformations'
    abp.schemas.app.session.getCurrentLoginInformations = abp.schemas.app.session.getCurrentLoginInformations || {};
    abp.schemas.app.session.getCurrentLoginInformations.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "GetCurrentLoginInformationsOutput",
        "type": "object",
        "properties": {
            "application": {
                "type": "object",
                "properties": {
                    "version": {
                        "type": "string"
                    },
                    "releaseDate": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "features": {
                        "type": "object"
                    }
                }
            },
            "user": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "name": {
                        "type": "string"
                    },
                    "surname": {
                        "type": "string"
                    },
                    "userName": {
                        "type": "string"
                    },
                    "emailAddress": {
                        "type": "string"
                    }
                }
            },
            "tenant": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "tenancyName": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                }
            }
        }
    }

    // controller 'role'
    abp.schemas.app.role = abp.schemas.app.role || {};
    // action 'create'
    abp.schemas.app.role.create = abp.schemas.app.role.create || {};
    abp.schemas.app.role.create.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "RoleDto",
        "type": "object",
        "required": [
            "name",
            "displayName"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "name": {
                "title": "RoleName",
                "type": "string",
                "maxLength": 32,
                "minLength": 0,
                "x-ui-grid": true
            },
            "displayName": {
                "title": "DisplayName",
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": true
            },
            "normalizedName": {
                "type": "string",
                "x-ui-grid": false
            },
            "description": {
                "type": "string",
                "maxLength": 5000,
                "minLength": 0,
                "x-ui-grid": false
            },
            "isStatic": {
                "type": "boolean",
                "x-ui-grid": false
            },
            "permissions": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.role.create.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "CreateRoleDto",
            "type": "object",
            "required": [
                "name",
                "displayName"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0
                },
                "displayName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "normalizedName": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 5000,
                    "minLength": 0
                },
                "isStatic": {
                    "type": "boolean"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-enum-action": "getAllPermissions",
                    "x-enum-valuefield": "name",
                    "x-enum-textfield": "displayName"
                }
            }
        },
    };
    // action 'getRoles'
    abp.schemas.app.role.getRoles = abp.schemas.app.role.getRoles || {};
    abp.schemas.app.role.getRoles.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ListResultDtoOfRoleListDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "isStatic": {
                            "type": "boolean"
                        },
                        "isDefault": {
                            "type": "boolean"
                        },
                        "creationTime": {
                            "type": "string",
                            "format": "date-time"
                        }
                    }
                }
            }
        }
    }
    abp.schemas.app.role.getRoles.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "GetRolesInput",
            "type": "object",
            "properties": {
                "permission": {
                    "type": "string"
                }
            }
        },
    };
    // action 'update'
    abp.schemas.app.role.update = abp.schemas.app.role.update || {};
    abp.schemas.app.role.update.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "RoleDto",
        "type": "object",
        "required": [
            "name",
            "displayName"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "name": {
                "title": "RoleName",
                "type": "string",
                "maxLength": 32,
                "minLength": 0,
                "x-ui-grid": true
            },
            "displayName": {
                "title": "DisplayName",
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": true
            },
            "normalizedName": {
                "type": "string",
                "x-ui-grid": false
            },
            "description": {
                "type": "string",
                "maxLength": 5000,
                "minLength": 0,
                "x-ui-grid": false
            },
            "isStatic": {
                "type": "boolean",
                "x-ui-grid": false
            },
            "permissions": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.role.update.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "UpdateRoleDto",
            "type": "object",
            "required": [
                "name",
                "displayName"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0,
                    "x-ui-group": "RoleDetails"
                },
                "displayName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0,
                    "x-ui-group": "RoleDetails"
                },
                "description": {
                    "type": "string",
                    "maxLength": 5000,
                    "minLength": 0,
                    "x-ui-group": "RoleDetails"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-ui-group": "RolePermissions",
                    "x-enum-action": "getAllPermissions",
                    "x-enum-valuefield": "name",
                    "x-enum-textfield": "displayName"
                }
            }
        },
    };
    // action 'delete'
    abp.schemas.app.role.delete = abp.schemas.app.role.delete || {};
    abp.schemas.app.role.delete.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt32",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'getAllPermissions'
    abp.schemas.app.role.getAllPermissions = abp.schemas.app.role.getAllPermissions || {};
    abp.schemas.app.role.getAllPermissions.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ListResultDtoOfPermissionDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
    // action 'getRoleForEdit'
    abp.schemas.app.role.getRoleForEdit = abp.schemas.app.role.getRoleForEdit || {};
    abp.schemas.app.role.getRoleForEdit.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "GetRoleForEditOutput",
        "type": "object",
        "properties": {
            "role": {
                "type": "object",
                "required": [
                    "name",
                    "displayName"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "name": {
                        "type": "string",
                        "maxLength": 32,
                        "minLength": 0
                    },
                    "displayName": {
                        "type": "string",
                        "maxLength": 64,
                        "minLength": 0
                    },
                    "description": {
                        "type": "string",
                        "maxLength": 5000,
                        "minLength": 0
                    },
                    "isStatic": {
                        "type": "boolean"
                    }
                }
            },
            "permissions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        }
                    }
                }
            },
            "grantedPermissionNames": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    }
    abp.schemas.app.role.getRoleForEdit.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDto",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'get'
    abp.schemas.app.role.get = abp.schemas.app.role.get || {};
    abp.schemas.app.role.get.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "RoleDto",
        "type": "object",
        "required": [
            "name",
            "displayName"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "name": {
                "title": "RoleName",
                "type": "string",
                "maxLength": 32,
                "minLength": 0,
                "x-ui-grid": true
            },
            "displayName": {
                "title": "DisplayName",
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-grid": true
            },
            "normalizedName": {
                "type": "string",
                "x-ui-grid": false
            },
            "description": {
                "type": "string",
                "maxLength": 5000,
                "minLength": 0,
                "x-ui-grid": false
            },
            "isStatic": {
                "type": "boolean",
                "x-ui-grid": false
            },
            "permissions": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.role.get.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt32",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'getAll'
    abp.schemas.app.role.getAll = abp.schemas.app.role.getAll || {};
    abp.schemas.app.role.getAll.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "PagedResultDtoOfRoleDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "name",
                        "displayName"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "name": {
                            "title": "RoleName",
                            "type": "string",
                            "maxLength": 32,
                            "minLength": 0,
                            "x-ui-grid": true
                        },
                        "displayName": {
                            "title": "DisplayName",
                            "type": "string",
                            "maxLength": 64,
                            "minLength": 0,
                            "x-ui-grid": true
                        },
                        "normalizedName": {
                            "type": "string",
                            "x-ui-grid": false
                        },
                        "description": {
                            "type": "string",
                            "maxLength": 5000,
                            "minLength": 0,
                            "x-ui-grid": false
                        },
                        "isStatic": {
                            "type": "boolean",
                            "x-ui-grid": false
                        },
                        "permissions": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "x-ui-grid": false
                        }
                    }
                }
            },
            "totalCount": {
                "type": "integer",
                "format": "int32"
            }
        }
    }
    abp.schemas.app.role.getAll.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "PagedResultRequestDto",
            "type": "object",
            "properties": {
                "maxResultCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 1.0
                },
                "skipCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 0.0
                }
            }
        },
    };

    // controller 'tenant'
    abp.schemas.app.tenant = abp.schemas.app.tenant || {};
    // action 'create'
    abp.schemas.app.tenant.create = abp.schemas.app.tenant.create || {};
    abp.schemas.app.tenant.create.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "TenantDto",
        "type": "object",
        "required": [
            "tenancyName",
            "name"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "tenancyName": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-group": "Details"
            },
            "name": {
                "type": "string",
                "maxLength": 128,
                "minLength": 0,
                "x-ui-group": "Details"
            },
            "isActive": {
                "type": "boolean",
                "x-ui-group": "Details"
            },
            "customActions": {
                "type": "array",
                "readonly": true,
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            },
            "features": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        },
                        "inputType": {
                            "type": "string"
                        },
                        "validator": {
                            "type": "string"
                        }
                    }
                },
                "x-ui-group": "Features",
                "x-ui-hideLabel": true,
                "x-type": "features",
                "x-ui-grid": false
            },
            "settings": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                },
                "x-ui-group": "Settings",
                "x-ui-hideLabel": true,
                "x-type": "settings",
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.tenant.create.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "CreateTenantDto",
            "type": "object",
            "required": [
                "tenancyName",
                "name",
                "adminEmailAddress"
            ],
            "properties": {
                "tenancyName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0
                },
                "adminEmailAddress": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0
                },
                "connectionString": {
                    "type": "string",
                    "maxLength": 1024,
                    "minLength": 0
                },
                "isActive": {
                    "type": "boolean"
                }
            }
        },
    };
    // action 'delete'
    abp.schemas.app.tenant.delete = abp.schemas.app.tenant.delete || {};
    abp.schemas.app.tenant.delete.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt32",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'get'
    abp.schemas.app.tenant.get = abp.schemas.app.tenant.get || {};
    abp.schemas.app.tenant.get.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "TenantDto",
        "type": "object",
        "required": [
            "tenancyName",
            "name"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "tenancyName": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-group": "Details"
            },
            "name": {
                "type": "string",
                "maxLength": 128,
                "minLength": 0,
                "x-ui-group": "Details"
            },
            "isActive": {
                "type": "boolean",
                "x-ui-group": "Details"
            },
            "customActions": {
                "type": "array",
                "readonly": true,
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            },
            "features": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        },
                        "inputType": {
                            "type": "string"
                        },
                        "validator": {
                            "type": "string"
                        }
                    }
                },
                "x-ui-group": "Features",
                "x-ui-hideLabel": true,
                "x-type": "features",
                "x-ui-grid": false
            },
            "settings": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                },
                "x-ui-group": "Settings",
                "x-ui-hideLabel": true,
                "x-type": "settings",
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.tenant.get.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt32",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'getAll'
    abp.schemas.app.tenant.getAll = abp.schemas.app.tenant.getAll || {};
    abp.schemas.app.tenant.getAll.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "PagedResultDtoOfTenantDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "tenancyName",
                        "name"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "tenancyName": {
                            "type": "string",
                            "maxLength": 64,
                            "minLength": 0,
                            "x-ui-group": "Details"
                        },
                        "name": {
                            "type": "string",
                            "maxLength": 128,
                            "minLength": 0,
                            "x-ui-group": "Details"
                        },
                        "isActive": {
                            "type": "boolean",
                            "x-ui-group": "Details"
                        },
                        "customActions": {
                            "type": "array",
                            "readonly": true,
                            "items": {
                                "type": "string"
                            },
                            "x-ui-grid": false
                        },
                        "features": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "displayName": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    },
                                    "inputType": {
                                        "type": "string"
                                    },
                                    "validator": {
                                        "type": "string"
                                    }
                                }
                            },
                            "x-ui-group": "Features",
                            "x-ui-hideLabel": true,
                            "x-type": "features",
                            "x-ui-grid": false
                        },
                        "settings": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "displayName": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                }
                            },
                            "x-ui-group": "Settings",
                            "x-ui-hideLabel": true,
                            "x-type": "settings",
                            "x-ui-grid": false
                        }
                    }
                }
            },
            "totalCount": {
                "type": "integer",
                "format": "int32"
            }
        }
    }
    abp.schemas.app.tenant.getAll.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "PagedResultRequestDto",
            "type": "object",
            "properties": {
                "maxResultCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 1.0
                },
                "skipCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 0.0
                }
            }
        },
    };
    // action 'update'
    abp.schemas.app.tenant.update = abp.schemas.app.tenant.update || {};
    abp.schemas.app.tenant.update.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "TenantDto",
        "type": "object",
        "required": [
            "tenancyName",
            "name"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "tenancyName": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0,
                "x-ui-group": "Details"
            },
            "name": {
                "type": "string",
                "maxLength": 128,
                "minLength": 0,
                "x-ui-group": "Details"
            },
            "isActive": {
                "type": "boolean",
                "x-ui-group": "Details"
            },
            "customActions": {
                "type": "array",
                "readonly": true,
                "items": {
                    "type": "string"
                },
                "x-ui-grid": false
            },
            "features": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        },
                        "inputType": {
                            "type": "string"
                        },
                        "validator": {
                            "type": "string"
                        }
                    }
                },
                "x-ui-group": "Features",
                "x-ui-hideLabel": true,
                "x-type": "features",
                "x-ui-grid": false
            },
            "settings": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "displayName": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                },
                "x-ui-group": "Settings",
                "x-ui-hideLabel": true,
                "x-type": "settings",
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.tenant.update.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "TenantDto",
            "type": "object",
            "required": [
                "tenancyName",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "tenancyName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0,
                    "x-ui-group": "Details"
                },
                "name": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0,
                    "x-ui-group": "Details"
                },
                "isActive": {
                    "type": "boolean",
                    "x-ui-group": "Details"
                },
                "customActions": {
                    "type": "array",
                    "readonly": true,
                    "items": {
                        "type": "string"
                    },
                    "x-ui-grid": false
                },
                "features": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "displayName": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            },
                            "inputType": {
                                "type": "string"
                            },
                            "validator": {
                                "type": "string"
                            }
                        }
                    },
                    "x-ui-group": "Features",
                    "x-ui-hideLabel": true,
                    "x-type": "features",
                    "x-ui-grid": false
                },
                "settings": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "displayName": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    },
                    "x-ui-group": "Settings",
                    "x-ui-hideLabel": true,
                    "x-type": "settings",
                    "x-ui-grid": false
                }
            }
        },
    };

    // controller 'localization'
    abp.schemas.app.localization = abp.schemas.app.localization || {};
    // action 'getAll'
    abp.schemas.app.localization.getAll = abp.schemas.app.localization.getAll || {};
    abp.schemas.app.localization.getAll.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "PagedResultDtoOfLocalizationDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "key",
                        "value"
                    ],
                    "properties": {
                        "source": {
                            "type": "string",
                            "readonly": true
                        },
                        "languageName": {
                            "type": "string",
                            "readonly": true
                        },
                        "key": {
                            "type": "string",
                            "readonly": true,
                            "maxLength": 256,
                            "minLength": 0,
                            "x-ui-grid-sortable": true
                        },
                        "default": {
                            "type": "string",
                            "readonly": true,
                            "x-ui-grid-sortable": true
                        },
                        "value": {
                            "type": "string",
                            "maxLength": 67108864,
                            "minLength": 0,
                            "x-ui-grid": false
                        }
                    }
                }
            },
            "totalCount": {
                "type": "integer",
                "format": "int32"
            }
        }
    }
    abp.schemas.app.localization.getAll.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "LocalizationResultRequestDto",
            "type": "object",
            "properties": {
                "sorting": {
                    "type": "string"
                },
                "skipCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 0.0
                },
                "maxResultCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 1.0
                },
                "languageSource": {
                    "type": "string",
                    "x-enum-action": "getSources",
                    "x-enum-valuefield": "name",
                    "x-enum-textfield": "name",
                    "x-enum-nonelabel": "All"
                },
                "languageName": {
                    "type": "string",
                    "x-enum-action": "getLanguages",
                    "x-enum-valuefield": "name",
                    "x-enum-textfield": "displayName",
                    "x-enum-nonelabel": "All"
                },
                "languageKey": {
                    "type": "string"
                },
                "notTranslatedOnly": {
                    "type": "boolean"
                }
            }
        },
    };
    // action 'save'
    abp.schemas.app.localization.save = abp.schemas.app.localization.save || {};
    abp.schemas.app.localization.save.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "Void",
        "type": "object"
    }
    abp.schemas.app.localization.save.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "LocalizationDto",
            "type": "object",
            "required": [
                "key",
                "value"
            ],
            "properties": {
                "source": {
                    "type": "string",
                    "readonly": true
                },
                "languageName": {
                    "type": "string",
                    "readonly": true
                },
                "key": {
                    "type": "string",
                    "readonly": true,
                    "maxLength": 256,
                    "minLength": 0,
                    "x-ui-grid-sortable": true
                },
                "default": {
                    "type": "string",
                    "readonly": true,
                    "x-ui-grid-sortable": true
                },
                "value": {
                    "type": "string",
                    "maxLength": 67108864,
                    "minLength": 0,
                    "x-ui-grid": false
                }
            }
        },
    };
    // action 'get'
    abp.schemas.app.localization.get = abp.schemas.app.localization.get || {};
    abp.schemas.app.localization.get.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "LocalizationDto",
        "type": "object",
        "required": [
            "key",
            "value"
        ],
        "properties": {
            "source": {
                "type": "string",
                "readonly": true
            },
            "languageName": {
                "type": "string",
                "readonly": true
            },
            "key": {
                "type": "string",
                "readonly": true,
                "maxLength": 256,
                "minLength": 0,
                "x-ui-grid-sortable": true
            },
            "default": {
                "type": "string",
                "readonly": true,
                "x-ui-grid-sortable": true
            },
            "value": {
                "type": "string",
                "maxLength": 67108864,
                "minLength": 0,
                "x-ui-grid": false
            }
        }
    }
    abp.schemas.app.localization.get.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfString",
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
    };
    // action 'getSources'
    abp.schemas.app.localization.getSources = abp.schemas.app.localization.getSources || {};
    abp.schemas.app.localization.getSources.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ListOfSourceDto",
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
    // action 'getLanguages'
    abp.schemas.app.localization.getLanguages = abp.schemas.app.localization.getLanguages || {};
    abp.schemas.app.localization.getLanguages.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "ListOfLanguageDto",
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                }
            }
        }
    }

    // controller 'language'
    abp.schemas.app.language = abp.schemas.app.language || {};
    // action 'create'
    abp.schemas.app.language.create = abp.schemas.app.language.create || {};
    abp.schemas.app.language.create.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "LanguageDto",
        "type": "object",
        "required": [
            "name",
            "displayName"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "name": {
                "title": "Code",
                "type": "string",
                "maxLength": 128,
                "minLength": 0
            },
            "displayName": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0
            },
            "icon": {
                "type": "string",
                "maxLength": 128,
                "minLength": 0
            },
            "enabled": {
                "type": "boolean"
            },
            "default": {
                "type": "boolean"
            }
        }
    }
    abp.schemas.app.language.create.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "LanguageDto",
            "type": "object",
            "required": [
                "name",
                "displayName"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "title": "Code",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0
                },
                "displayName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "icon": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0
                },
                "enabled": {
                    "type": "boolean"
                },
                "default": {
                    "type": "boolean"
                }
            }
        },
    };
    // action 'update'
    abp.schemas.app.language.update = abp.schemas.app.language.update || {};
    abp.schemas.app.language.update.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "LanguageDto",
        "type": "object",
        "required": [
            "name",
            "displayName"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "name": {
                "title": "Code",
                "type": "string",
                "maxLength": 128,
                "minLength": 0
            },
            "displayName": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0
            },
            "icon": {
                "type": "string",
                "maxLength": 128,
                "minLength": 0
            },
            "enabled": {
                "type": "boolean"
            },
            "default": {
                "type": "boolean"
            }
        }
    }
    abp.schemas.app.language.update.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "LanguageDto",
            "type": "object",
            "required": [
                "name",
                "displayName"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "title": "Code",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0
                },
                "displayName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "icon": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 0
                },
                "enabled": {
                    "type": "boolean"
                },
                "default": {
                    "type": "boolean"
                }
            }
        },
    };
    // action 'delete'
    abp.schemas.app.language.delete = abp.schemas.app.language.delete || {};
    abp.schemas.app.language.delete.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt32",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'get'
    abp.schemas.app.language.get = abp.schemas.app.language.get || {};
    abp.schemas.app.language.get.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "LanguageDto",
        "type": "object",
        "required": [
            "name",
            "displayName"
        ],
        "properties": {
            "id": {
                "type": "integer",
                "format": "int32"
            },
            "name": {
                "title": "Code",
                "type": "string",
                "maxLength": 128,
                "minLength": 0
            },
            "displayName": {
                "type": "string",
                "maxLength": 64,
                "minLength": 0
            },
            "icon": {
                "type": "string",
                "maxLength": 128,
                "minLength": 0
            },
            "enabled": {
                "type": "boolean"
            },
            "default": {
                "type": "boolean"
            }
        }
    }
    abp.schemas.app.language.get.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "EntityDtoOfInt32",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int32"
                }
            }
        },
    };
    // action 'getAll'
    abp.schemas.app.language.getAll = abp.schemas.app.language.getAll || {};
    abp.schemas.app.language.getAll.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "PagedResultDtoOfLanguageDto",
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "name",
                        "displayName"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "name": {
                            "title": "Code",
                            "type": "string",
                            "maxLength": 128,
                            "minLength": 0
                        },
                        "displayName": {
                            "type": "string",
                            "maxLength": 64,
                            "minLength": 0
                        },
                        "icon": {
                            "type": "string",
                            "maxLength": 128,
                            "minLength": 0
                        },
                        "enabled": {
                            "type": "boolean"
                        },
                        "default": {
                            "type": "boolean"
                        }
                    }
                }
            },
            "totalCount": {
                "type": "integer",
                "format": "int32"
            }
        }
    }
    abp.schemas.app.language.getAll.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "PagedResultRequestDto",
            "type": "object",
            "properties": {
                "maxResultCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 1.0
                },
                "skipCount": {
                    "type": "integer",
                    "format": "int32",
                    "maximum": 2147483647.0,
                    "minimum": 0.0
                }
            }
        },
    };

    // controller 'configuration'
    abp.schemas.app.configuration = abp.schemas.app.configuration || {};
    // action 'changeUiTheme'
    abp.schemas.app.configuration.changeUiTheme = abp.schemas.app.configuration.changeUiTheme || {};
    abp.schemas.app.configuration.changeUiTheme.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "ChangeUiThemeInput",
            "type": "object",
            "required": [
                "theme"
            ],
            "properties": {
                "theme": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0
                }
            }
        },
    };

    // controller 'account'
    abp.schemas.app.account = abp.schemas.app.account || {};
    // action 'isTenantAvailable'
    abp.schemas.app.account.isTenantAvailable = abp.schemas.app.account.isTenantAvailable || {};
    abp.schemas.app.account.isTenantAvailable.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "IsTenantAvailableOutput",
        "type": "object",
        "properties": {
            "state": {
                "type": "integer",
                "x-enumNames": [
                    "Available",
                    "InActive",
                    "NotFound"
                ],
                "enum": [
                    1,
                    2,
                    3
                ]
            },
            "tenantId": {
                "type": "integer",
                "format": "int32"
            }
        }
    }
    abp.schemas.app.account.isTenantAvailable.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "IsTenantAvailableInput",
            "type": "object",
            "required": [
                "tenancyName"
            ],
            "properties": {
                "tenancyName": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                }
            }
        },
    };
    // action 'register'
    abp.schemas.app.account.register = abp.schemas.app.account.register || {};
    abp.schemas.app.account.register.returnValue = {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "RegisterOutput",
        "type": "object",
        "properties": {
            "canLogin": {
                "type": "boolean"
            }
        }
    }
    abp.schemas.app.account.register.parameters = {
        input: {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "title": "RegisterInput",
            "type": "object",
            "required": [
                "name",
                "surname",
                "userName",
                "emailAddress",
                "password"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "surname": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 0
                },
                "userName": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 0
                },
                "emailAddress": {
                    "type": "string",
                    "format": "email",
                    "maxLength": 256,
                    "minLength": 0
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 0
                },
                "captchaResponse": {
                    "type": "string"
                }
            }
        },
    };

})();
